[build]
  publish = "_site"
  command = "npm run build"
[[redirects]]
  from = "https://www.nerja.casa"
  to = "https://www.nerja.holiday"
  status = 301
  force = true
  [[redirects]]
  from = "https://nerja.casa"
  to = "https://nerja.holiday"
  status = 301
  force = true